---
- name: Check Expiration Date and Renew if Less than 30days
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    websites_to_check:
      - google.ca
      - facebook.com
      - twitter.com
  tasks:
    - name: Get x509 TLS Certificate Informations
      shell: >
        echo | 
        openssl s_client -connect {{ item }}:443 2>/dev/null | openssl x509 -noout -dates
      register: openssl_output
      ignore_errors: yes
      with_items: "{{ websites_to_check }}"

    - name: Extract notAfter Expiry Date
      set_fact: 
        expiration_date: "{{ expiration_date | default([]) + [item.stdout_lines[1] | regex_replace('notAfter=', '')]  }}"
      with_items: "{{ openssl_output.results }}"
      loop_control:
        loop_var: item

    - name: Calculate days before Cert expires
      set_fact:
        days_before_expiry: "{{ days_before_expiry | default([]) + [(item | to_datetime('%b %d %H:%M:%S %Y GMT') - now()).days] }}"
      with_items: "{{ expiration_date }}"

    - name: Loop Print back Days for each site
      debug:
        msg: "{{item.0}}days left to {{item.1}}"
      with_together:
        - "{{days_before_expiry}}"
        - "{{websites_to_check}}"
